# Generated by Django 5.2.8 on 2025-12-23 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('channel_arn', models.CharField(blank=True, max_length=255)),
                ('stream_key', models.CharField(blank=True, max_length=255)),
                ('ingest_endpoint', models.CharField(blank=True, max_length=255)),
                ('playback_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('live', 'Live'), ('ended', 'Ended')], default='preparing', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewer_count', models.IntegerField(default=0)),
                ('peak_viewers', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStreamComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='livestream.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestream_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStreamView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('livestream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='livestream.livestream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livestream_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['-created_at'], name='livestream__created_efb546_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['user', '-created_at'], name='livestream__user_id_bd70b6_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['status'], name='livestream__status_73cb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='livestreamcomment',
            index=models.Index(fields=['livestream', 'created_at'], name='livestream__livestr_a12ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='livestreamview',
            index=models.Index(fields=['livestream', '-joined_at'], name='livestream__livestr_a41c14_idx'),
        ),
    ]
