# Generated by Django 5.2.8 on 2026-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_name',
            field=models.CharField(max_length=150, verbose_name='profile name'),
        ),
    ]
