# Generated by Django 5.2.8 on 2025-12-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/', verbose_name='cover photo'),
        ),
    ]
