# Generated by Django 5.2.8 on 2025-12-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_conver_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conver_photo',
            new_name='cover_photo',
        ),
    ]
