# Generated by Django 5.2.8 on 2025-11-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_lock',
            field=models.BooleanField(default=False, verbose_name='profile lock'),
        ),
    ]
