# Generated by Django 5.2.8 on 2025-12-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('payment_completed', 'Payment Completed'), ('packed', 'Packed'), ('sent', 'Sent'), ('received', 'Received')], default='order_created', max_length=20),
        ),
    ]
