# Generated by Django 5.2.8 on 2025-11-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_caption',
            field=models.TextField(blank=True, help_text='Caption added when sharing a post'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='social.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('post_share', 'Post Share'), ('comment_like', 'Comment Like'), ('society_invite', 'Society Invite'), ('society_join', 'Society Join Request')], max_length=30),
        ),
    ]
