# Generated by Django 5.2.8 on 2025-12-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='society_backgrounds/'),
        ),
    ]
