# Generated by Django 5.2.8 on 2025-12-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_society_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='society_profiles/'),
        ),
    ]
